### ISSUE TITLE
KubeJsonApi is not accessible from Renderer.K8sApi

### ISSUE THREAD

**Issue by pmdawood** [kontena/lens#6255]
**Describe the bug**
KubeJsonApi is not accessible from Renderer.K8sApi.

This code was running till 5.4.4 Renderer.K8sApi.KubeJsonApi.forCluster(clusterId); after we upgraded to 6.0.2
compiler throws error Property 'KubeJsonApi' does not exist on type 'typeof import("/ui/lens/node_modules/@k8slens/extensions/dist/src/extensions/renderer-api/k8s-api")'

**To Reproduce**
run this  Renderer.K8sApi.KubeJsonApi.forCluster(clusterId) , compiler complaint 'KubeJsonApi' does not exist
**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 6.0.2
- OS: [e.g. OSX]: mac
- Installation method (e.g. snap or AppImage in Linux):
auto upgrade from 5.4.4 to 6.0.2
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
